language: python
addons: 
  SonarCloud:
    organization: "evanlavic"
    token: 1342e1ad03aea8205fd390811d4a8c667017ed15
install:
  - pip install coverage coveralls
  - pip install -I -r requirements.txt
script:
  - coverage run -a --sorce=/ test_lab4.py
after_success:
  - coveralls