language: python
jobs:
  include:
  - name: "Python 3 on Windows"
    os: windows
    language: shell
    before_install:
      - choco install python
      - choco install pip
      - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - python lab 4.py || python lab 4.py